### ISSUE TITLE
References are missing when project published to "browser" section and user is not logged 

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#53]
![image](https://user-images.githubusercontent.com/72507850/103903458-d1ad4280-50f3-11eb-99bf-fbc4d8f2f809.png)

![image](https://user-images.githubusercontent.com/72507850/103903641-120cc080-50f4-11eb-8a24-88cee8d72c0d.png)

The references are missing they should be displayed author(s), year the same way as when tables are exported

**Comment by damian-garrido** [comment]
@MJWainwright this issue was fixed on the test server

**Comment by MJWainwright** [comment]
Nope, still not appearing. Remember I am meaning when the user is not logged-in but rather is viewing the published project from the "browse" tab:

You can see below that the references are missing. And I did clear the cache.
![image](https://user-images.githubusercontent.com/72507850/104020838-bf93d880-51b5-11eb-8764-9c4ab66d9989.png)
![image](https://user-images.githubusercontent.com/72507850/104020860-c6bae680-51b5-11eb-81a8-7e5d5316be8e.png)

**Comment by damian-garrido** [comment]
aha! ok, i confirm that doesnt appear when you are not logged

**Comment by MJWainwright** [comment]
@damian-garrido  I am still getting this problem. I don't think it is fixed. When I publish a project on either the Test or the Production server everything looks normal while I am still logged-in. But when I logout and then go to Browse, I do not see the projects correctly at all:
![image](https://user-images.githubusercontent.com/72507850/115988148-44153600-a5b0-11eb-994f-5c5b06ee1ac4.png)

**Comment by MJWainwright** [comment]
@damian-garrido I'm going to close this. Although the publish to database on the test server doesn't seem to work at all, it does seem to be working on the production server
